# Generated by Django 5.1.2 on 2024-10-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="cidade",
            field=models.CharField(default="Cidade Padrão", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="email@exemplo.com", max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="endereco",
            field=models.TextField(default="Endereço Padrão", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="primeiro_nome",
            field=models.CharField(default="nome padrao", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="segundo_nome",
            field=models.CharField(default="nome padrao", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="senha",
            field=models.CharField(default="123", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="usuario",
            field=models.CharField(default="user", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
