# Generated by Django 5.1.2 on 2024-10-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_product_remove_order_user_order_cidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idade",
            field=models.IntegerField(default=0),
        ),
    ]
