name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2 
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: View Poetry help
        run: poetry --help

      - name: Install dependencies
        run: poetry install

      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}  
          SQL_DATABASE: lojadelivros_test_db  
          SQL_USER: user123  
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}  
          SQL_HOST: localhost  
          SQL_PORT: 5432  
        run: |
          poetry run python manage.py test

      - name: Run Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
